//
// Created by Camila Alvarez on 16-08-16.
//

#ifndef WHERETOBUYITEVALUATION_MEASURECALCULATOR_HPP
#define WHERETOBUYITEVALUATION_MEASURECALCULATOR_HPP
class MeasureCalculator{
};
#endif //WHERETOBUYITEVALUATION_MEASURECALCULATOR_HPP
